### ISSUE TITLE
`pip install vars-gridview` fails with python 3.12

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-gridview#77]
The pip install fails with Python 3.12 due to the removal of the long-deprecated `pkgutil.ImpImporter` class. Note that this is a pip issue and is not specific to vars-gridview.  I found some notes [here](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) but the proposed workarounds did not fix the issue. Downgrading to 3.11 worked fine.

### Steps to reproduce:

```
conda create -n vars-gridview python=3.12
conda activate vars-gridview
pip install vars-gridview
```

### Output

```text
Collecting vars-gridview
  Downloading vars_gridview-0.12.1-py3-none-any.whl.metadata (2.5 kB)
Collecting beholder-client<0.2.0,>=0.1.0 (from vars-gridview)
  Downloading beholder_client-0.1.0-py3-none-any.whl.metadata (1.5 kB)
Collecting dreamsim<0.2.0,>=0.1.3 (from vars-gridview)
  Downloading dreamsim-0.1.3-py3-none-any.whl.metadata (7.5 kB)
Collecting opencv-python<5.0.0.0,>=4.5.5.62 (from vars-gridview)
  Downloading opencv-python-4.10.0.82.tar.gz (95.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 MB 35.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/vars-gridview/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/miniconda3/envs/vars-gridview/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/envs/vars-gridview/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/envs/vars-gridview/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/envs/vars-gridview/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/zn/j87g9m_s1jz2gnm_g0r_s53h0000gn/T/pip-build-env-nl1z61jp/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/zn/j87g9m_s1jz2gnm_g0r_s53h0000gn/T/pip-build-env-nl1z61jp/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/zn/j87g9m_s1jz2gnm_g0r_s53h0000gn/T/pip-build-env-nl1z61jp/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kevinsbarnard** [comment]
This seems to be an issue with the build of opencv-python on Apple Silicon. I followed the steps you provided on my machine (Linux 6.5.0-35-generic with conda 24.5.0) without issue.

Is there a possibility to use the bundled application? I haven't built one for the latest version (v0.12.1) but I can get on that... but it may be worth trying an earlier version (e.g. [v0.11.0](https://github.com/mbari-org/vars-gridview/releases/tag/v0.11.0)) to test as the VL has had success with this approach.

**Comment by hohonuuli** [comment]
I was able to get it to build on python 3.11, but I can try the v0.11.0 on OSU's hardware  too. The catch is that they are running on postgres.

**Comment by kwalz** [comment]
This is still an issue for Larissa's machine as well, we'd like to have the bundled app for V0.12.1 when available, thanks so much!

**Comment by lonnylundsten** [comment]
@kevinsbarnard I think this issue is resolved? One thing I have found is that one of the required libraries, pymssql, doesn't install correctly so if one were to install using a requirements.txt it might appear to have installed pymmsql correctly but ay not have. Also it may depend upon python version and whether a user is using an intel or apple silicon. 

To fix the pymssql issue, I 'pip uninstall pymssql' and then 'pip install pymssql --no-binary :all:'

**Comment by kevinsbarnard** [comment]
@lonnylundsten Would you mind testing if this is still an issue in the latest version of VARS GridView (v0.16.3)? I think so too- also, all SQL is gone.

**Comment by lonnylundsten** [comment]
From what I can tell it seems good. I will try installing on Larissa's computer to do a better test.

**Comment by lonnylundsten** [comment]
For this version, 16.3, I had to 1) manually install pydantic and 2) change the config login to https.

**Comment by lonnylundsten** [comment]
@kevinsbarnard Continuing to test here...I started with a clean python 3.13.2 environment. Installed vars-gridview 16.3 and it failed with a database connection error. I went back to 3.13.1 and it worked. Then went back to 3.13.2, installed pymssql, and it worked. Is there some other dependency relying on pymssql? beholder-client or sharktopoda-client? 

Still having to install pymssql this way too:
pip install pymssql --no-binary :all:

**Comment by lonnylundsten** [comment]
Using vars-gridview in python 3.13.1 or 3.13.2 gives the following error when querying for video_sequence_name = Ventana 4358

`vars-gridview
2025-02-06 11:33:46.743 python[31187:6610706] +[IMKClient subclass]: chose IMKClient_Modern
Using cached /Users/lonny/Library/Caches/VARS GridView/dreamsim
Using cache found in /Users/lonny/Library/Caches/VARS GridView/dreamsim/facebookresearch_dino_main
/Users/lonny/.pyenv/versions/3.13.1/lib/python3.13/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Traceback (most recent call last):
  File "/Users/lonny/.pyenv/versions/3.13.1/lib/python3.13/site-packages/vars_gridview/__main__.py", line 477, in _do_query
    query_data = query(query_request)
  File "/Users/lonny/.pyenv/versions/3.13.1/lib/python3.13/site-packages/vars_gridview/lib/m3/operations.py", line 305, in query
    raise e
  File "/Users/lonny/.pyenv/versions/3.13.1/lib/python3.13/site-packages/vars_gridview/lib/m3/operations.py", line 302, in query
    response.raise_for_status()`

**Comment by kevinsbarnard** [comment]
@lonnylundsten, please confirm that you have a completely clean environment and are installing `vars-gridview==0.16.3` fresh:

```
python -m venv .venv
. .venv/bin/activate
python -m pip install --force-reinstall vars-gridview==0.16.3 pydantic
...
vars-gridview
```

By the way, I've fixed the issue with pydantic (for future versions) -- it was just missing from the list of dependencies.

**Comment by kevinsbarnard** [comment]
Hmm, I'll look into why you're getting that 404

**Comment by kevinsbarnard** [comment]
Pydantic issue is fixed in v0.16.4

**Comment by kevinsbarnard** [comment]
@lonnylundsten I've created a new issue to track the 404 problem you're seeing: https://github.com/mbari-org/vars-gridview/issues/89

I'm going to close this issue as the install seems to be working ok in Python 3.12.
